# Generated by Django 5.1.5 on 2025-01-30 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
    ]
