# Generated by Django 5.1.5 on 2025-01-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20250130_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logdetails',
            options={'verbose_name': 'Log Detail', 'verbose_name_plural': 'Log Details'},
        ),
        migrations.AlterModelOptions(
            name='parkingdetails',
            options={'verbose_name': 'Parking Detail', 'verbose_name_plural': 'Parking Details'},
        ),
        migrations.AlterModelOptions(
            name='parkinglot',
            options={'verbose_name': 'Parking Lot', 'verbose_name_plural': 'Parking Lots'},
        ),
        migrations.AlterModelOptions(
            name='parkingplace',
            options={'verbose_name': 'Parking Place', 'verbose_name_plural': 'Parking Places'},
        ),
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'verbose_name': 'Payment Detail', 'verbose_name_plural': 'Payment Details'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'verbose_name': 'Vehicle Type', 'verbose_name_plural': 'Vehicle Types'},
        ),
    ]
