# Generated by Django 5.1.5 on 2025-01-31 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPlace',
            fields=[
                ('place_id', models.AutoField(primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('vehicle_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle_reg_no', models.CharField(max_length=50, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingLot',
            fields=[
                ('lot_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_before', models.CharField(max_length=50)),
                ('status_after', models.CharField(max_length=50)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_lots', to='parking.parkingplace')),
            ],
        ),
        migrations.CreateModel(
            name='ParkingDetail',
            fields=[
                ('parking_id', models.AutoField(primary_key=True, serialize=False)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('parking_duration', models.DurationField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_details', to='parking.parkinglot')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_details', to='parking.parkingplace')),
                ('occupied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_details', to='parking.user')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_details', to='parking.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_date', models.DateTimeField()),
                ('payment_status', models.CharField(max_length=50)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='parking.parkingdetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='parking.user')),
            ],
        ),
        migrations.CreateModel(
            name='LogDetail',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='parking.user')),
            ],
        ),
    ]
